#' This is the function for calculating root mean square error
#'
#' @param decon File directory for single cell reference file.
#' @param gt File directory for realbulk reference.
#'
#' @returns Return the RMSE value
#' @export Calculate_RMSE
Calculate_RMSE <- function(decon, gt) {
  result <- c()
  len <- dim(gt)[1]
  gt <- gt[,colnames(decon)]
  for (i in 1:len) {
    result <- c(result,
                sqrt(sum((decon[i,] - gt[i,])**2)/len))
  }
  return(result)
}



#' This is the function for CosGeneGate deconvolution - realbulk mode
#'
#' @param sc_profile File directory for single cell reference file.
#' @param realbulk_profile File directory for realbulk reference.
#' @param realbulk_gt File directory for the groundtruth of realbulk reference.
#' @param mkg_file Marker gene file generated by CosGeneGate.
#' @param index Numbe of marker genes to be iterated.
#' @param plot_line TRUE to plot the graph of error vs. # of marker genes, FALSE otherwise.
#'
#' @return Return the optimized single cell reference profile.
#' @import MuSiC dplyr SingleCellExperiment zellkonverter Matrix MCMCpack SummarizedExperiment
#' @importFrom hash hash
#' @importFrom utils read.csv read.table
#' @export deconvolution_realbulk_mode
deconvolution_realbulk_mode <- function(sc_profile,
                                        realbulk_profile,
                                        realbulk_gt,
                                        mkg_file,
                                        index = c(2,3,4,5,6,7,8,9,10,12,14,16,18,20,25,30,35,40,45,50),
                                        plot_line=FALSE) {
  # Read single cell data
  sc.ref <- readH5AD(sc_profile)
  names(assays(sc.ref)) <- "counts"
  # Read mixture data
  real.bulk <- as.matrix(read.table(realbulk_profile, header=TRUE, sep="\t",
                                    row.names=1,
                                    as.is=TRUE))
  # Read markers
  marker.gene <- read.csv(mkg_file, sep='\t', check.names=FALSE)
  marker.gene <- marker.gene[, !(names(marker.gene) %in% c('X'))]
  # Read ground truth
  groundtruth <- read.csv(realbulk_gt, sep='\t', check.names=FALSE)
  groundtruth <- groundtruth[, !(names(groundtruth) %in% c('X'))]

  mk.test <- hash()
  # mk.test.index <- c(45,50)
  mk.test.index <- index
  for (npct in mk.test.index) {
    mkg <- c()
    for (ct in colnames(marker.gene)) {
      mkg <- c(mkg, marker.gene[0:npct, ct])
    }
    mk.test[npct] <- mkg
  }
  mk.test.RMSE <- hash()
  plt.RMSE <- c()
  for (npct in mk.test.index) {
    decon <- music_prop(bulk.mtx = real.bulk,
                        sc.sce = sc.ref,
                        clusters = 'label',
                        samples = 'sample_id',
                        markers=mk.test[[as.character(npct)]])
    mk.test.RMSE[npct] <- mean(Calculate_RMSE(decon$Est.prop.weighted, groundtruth))
    plt.RMSE <- c(plt.RMSE, mean(Calculate_RMSE(decon$Est.prop.weighted, groundtruth)))
  }
  min_err <- min(unlist(as.list(mk.test.RMSE)))
  num_marker <- names(which(unlist(as.list(mk.test.RMSE)) == min_err))
  optimal_marker <- mk.test[[num_marker]]
  if (plot_line == TRUE) {
    plot(index, plt.RMSE, type = "b", pch = 19, col = "black", xlab = "Number of markers per cell type", ylab = "Mean RMSE")
  }
  return(sc.ref[optimal_marker])
}
